CREATE TABLE task (
    pk BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status int(3) NOT NULL,
    priority int(3) NOT NULL,
    due_date TIMESTAMP,
    user_fk BIGINT NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    FOREIGN KEY (user_fk) REFERENCES user(id) ON DELETE CASCADE
);
